### ISSUE TITLE
Permalink icon isn't very visible in dark mode

### ISSUE THREAD

**Issue by joshtemple** [rohit-gohri/redocusaurus#18]
<img width="162" alt="image" src="https://user-images.githubusercontent.com/8672171/114587810-9d45a700-9c4b-11eb-894b-ede029492def.png">

The permalink icon is black in dark mode but would be more visible in white.

**Comment by rohit-gohri** [comment]
Fixed in v0.3.3

**Comment by joshtemple** [comment]
Hey @rohit-gohri! This is definitely fixed for `h1` but the icon still shows up black for `h2` (for each route in the API).

**Comment by rohit-gohri** [comment]
Fixed in v0.3.4 (finally)
